### extensión que simula peticiones de front
@api = http://localhost:3000/inventario/
@getEmpreas = http://localhost:3000/Empresa_Suministradora/

### visitas tecnicas
@getVisitas = http://localhost:3000/Visita_Tecnica/


GET {{api}}
###
POST {{api}}
Content-Type: "application/json"

{
    "Pk_Id_Producto":11,
    "Nombre_Producto": "monitor",
    "Referencia":"multiformat",
    "Marca": "tvlogic",
    "Numero_de_Orden":1059,
    "Fecha_de_Compra":"09/05/2024",
    "cantidad":23123,
}

###
GET {{api}}/1
###
DELETE {{api}}/1
###
PUT {{api}}


### Empresas
GET {{getEmpreas}}
###

### visitas
GET {{{{getVisitas}}}}
###
